language: python
sudo: false
cache: pip

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27,flask
  - python: 3.6
    env: TOXENV=py36,flask,django,async
  - python: 3.7
    dist: xenial
    sudo: true
    env: TOXENV=py37,flask,django,async

install:
  - pip install -U setuptools
  - pip install tox

script: tox

after_success:
  - tox -e codecov

notifications:
  email: false

branches:
  except:
    - /wip-.*/
